services:
  #  app:
  #    build:
  #      context: ./
  #      dockerfile: Dockerfile
  #    image: test/app:v1
  #    container_name: app
  #    ports:
  #      - "80:1323"
  #    restart: on-failure
  #    environment:
  #      - POSTGRES_HOST=app_db
  #    depends_on:
  #      app_db:
  #        condition: service_healthy
  #      app_redis:
  #        condition: service_healthy

  app_db:
    image: postgres:latest
    container_name: app_db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=digitalenvision
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d digitalenvision -U admin']
      interval: 10s
      timeout: 5s
      retries: 5

#  app_redis:
#    image: redis:latest
#    container_name: app_redis
#    ports:
#      - "6379:6379"
#    environment:
#      - REDIS_PASSWORD=1234
#      - REDIS_PORT=6379
#      - REDIS_DATABASES=16
#    restart: always
#    healthcheck:
#      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
#      interval: 1s
#      timeout: 3s
#      retries: 5

volumes:
  postgres_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /home/zer0day/docker-volume/pg-db
    #   o: bind
